# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Dell Inc, or its subsidiaries.
---
version: "3.7"

services:

  opi-test:
    image: docker.io/library/alpine:3.19
    networks:
      - opi

networks:
  opi:
